# .gitlab-ci.yml
# SEE: https://gitlab.com/nfreear/gaad-widget/-/ci/lint
# https://gitlab.com/gitlab-examples/nodejs/blob/master/.gitlab-ci.yml
# https://gist.github.com/thornbill/b4f44ac81106fd539d5f493a269bf25b

# https://hub.docker.com/r/library/node/tags/
image: node:6

variables:
  GIT_DEPTH: 8

cache:
  paths:
  - node_modules/

stages:
  - test

before_script:
  - node -v
  - npm -v
  - npm install

job 1:
  stage: test
  script:
    - npm run build
    - npm test
    - npm run serve-ci & sleep 5; npm run pa11y-ci
  artifacts:
    # untracked: true
    paths:
      - dist/*
      - data/*
    # only:
    #   - tags

after_script:
  - npm run ps
  - npm run kill-server
  - npm pack
  - nvm --version

# End.
