language: node_js
node_js:
  - "4"
  - "6"

git:
  depth: 8

install:
  - npm install

script:
  - npm run build
  - npm test

after_script:
  - ls -alh dist
  - ls -alh data
  - cat dist/gaad-widget.min.js

# End.
